# Generated by Django 4.2.9 on 2026-10-02 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请数量')),
                ('receiver', models.CharField(max_length=100, verbose_name='领用人')),
                ('receiver_dept', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='领用事由')),
                ('risk_level', models.CharField(choices=[('normal', '普通物资'), ('high', '高风险物资')], max_length=10, verbose_name='风险等级快照')),
                ('status', models.CharField(choices=[('signing', '签署中'), ('released', '已放行'), ('rejected', '已拒绝'), ('expired', '已过期'), ('blocked', '权限阻止')], default='signing', max_length=20, verbose_name='状态')),
                ('expires_at', models.DateTimeField(verbose_name='签署截止时间')),
                ('closed_reason', models.CharField(blank=True, max_length=200, verbose_name='终态原因')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='乐观锁版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '放行申请',
                'verbose_name_plural': '放行申请',
                'db_table': 'wh_release_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='risk_level',
            field=models.CharField(choices=[('normal', '普通物资'), ('high', '高风险物资')], default='normal', max_length=10, verbose_name='风险等级'),
        ),
        migrations.CreateModel(
            name='ReleaseSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('applicant', '申请人'), ('first_reviewer', '第一复核人'), ('final_releaser', '最终放行人')], max_length=20, verbose_name='签署角色')),
                ('action', models.CharField(choices=[('approved', '同意'), ('rejected', '拒绝')], max_length=10, verbose_name='签署动作')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='签署意见')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='签署时间')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='warehouse.releaserequest', verbose_name='放行申请')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_signatures', to=settings.AUTH_USER_MODEL, verbose_name='签署人')),
            ],
            options={
                'verbose_name': '放行签署记录',
                'verbose_name_plural': '放行签署记录',
                'db_table': 'wh_release_signature',
                'ordering': ['signed_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='releaserequest',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_requests', to='warehouse.goods', verbose_name='货物'),
        ),
        migrations.AddField(
            model_name='releaserequest',
            name='stock_out',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_request', to='warehouse.stockout', verbose_name='出库记录'),
        ),
        migrations.AddConstraint(
            model_name='releasesignature',
            constraint=models.UniqueConstraint(fields=('request', 'role'), name='uniq_release_role_signature'),
        ),
    ]
